### ISSUE TITLE
Analysis component crashes

### ISSUE THREAD

**Issue by yamalight** [hobbit-project/platform#105]
Analysis component crashes on "feature/leaderboards" branch during startup with the following log:
```
2017-09-04 15:04:27,733 WARN [org.hobbit.core.components.AbstractComponent] - <Couldn't connect to RabbitMQ with try #0. Next try in 5000ms.>
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:91)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:670)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:722)
	at org.hobbit.core.components.AbstractComponent.createConnection(AbstractComponent.java:103)
	at org.hobbit.core.components.AbstractComponent.init(AbstractComponent.java:89)
	at org.hobbit.analysis.AnalysisComponent.init(AnalysisComponent.java:52)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2017-09-04 15:04:32,738 WARN [org.hobbit.core.components.AbstractComponent] - <Couldn't connect to RabbitMQ with try #1. Next try in 10000ms.>
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.FrameHandlerFactory.create(FrameHandlerFactory.java:32)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:34)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:91)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:670)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:722)
	at org.hobbit.core.components.AbstractComponent.createConnection(AbstractComponent.java:103)
	at org.hobbit.core.components.AbstractComponent.init(AbstractComponent.java:89)
	at org.hobbit.analysis.AnalysisComponent.init(AnalysisComponent.java:52)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
2017-09-04 15:04:42,956 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
java.io.IOException
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:106)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:102)
	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1119)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:382)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:374)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicConsume(AutorecoveringChannel.java:370)
	at org.hobbit.analysis.AnalysisComponent.init(AnalysisComponent.java:58)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'hobbit.controller-analysis' in vhost '/', class-id=60, method-id=20)
	at com.rabbitmq.utility.ValueOrException.getValue(ValueOrException.java:67)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:33)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:361)
	at com.rabbitmq.client.impl.ChannelN.basicConsume(ChannelN.java:1117)
	... 5 more
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'hobbit.controller-analysis' in vhost '/', class-id=60, method-id=20)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:484)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:321)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:144)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:91)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:556)
	at java.lang.Thread.run(Thread.java:745)
```

Following diff fixes it (at least makes it start correctly):
```diff
diff --git a/analysis-component/src/main/java/org/hobbit/analysis/AnalysisComponent.java b/analysis-component/src/main/java/org/hobbit/analysis/AnalysisComponent.java
index 5f7b91e..f6c2c0c 100644
--- a/analysis-component/src/main/java/org/hobbit/analysis/AnalysisComponent.java
+++ b/analysis-component/src/main/java/org/hobbit/analysis/AnalysisComponent.java
@@ -40,7 +40,7 @@ public class AnalysisComponent extends AbstractComponent {
     private static final Logger LOGGER = LoggerFactory.getLogger(AnalysisComponent.class);
     private static final String GRAPH_URI = Constants.PUBLIC_RESULT_GRAPH_URI;
     protected RabbitQueue controller2AnalysisQueue;
-//    protected RabbitQueue analysisQueue;
+    protected RabbitQueue analysisQueue;
     protected QueueingConsumer consumer;
 
     private Model experimentModel = null;
@@ -52,7 +52,7 @@ public class AnalysisComponent extends AbstractComponent {
         super.init();
         //initialize the controller_to_analysis queue
         controller2AnalysisQueue =  incomingDataQueueFactory.createDefaultRabbitQueue(Constants.RABBIT_MQ_HOST_NAME_KEY);
-//        analysisQueue = createDefaultRabbitQueue(Constants.CONTROLLER_2_ANALYSIS_QUEUE_NAME);
+        analysisQueue = incomingDataQueueFactory.createDefaultRabbitQueue(Constants.CONTROLLER_2_ANALYSIS_QUEUE_NAME);
         consumer = new QueueingConsumer(controller2AnalysisQueue.channel);
         controller2AnalysisQueue.channel.basicConsume(controller2AnalysisQueue.name, false, consumer);
         controller2AnalysisQueue.channel.basicConsume(Constants.CONTROLLER_2_ANALYSIS_QUEUE_NAME, false, consumer);
@@ -107,7 +107,7 @@ public class AnalysisComponent extends AbstractComponent {
     @Override
     public void close() throws IOException {
         IOUtils.closeQuietly(controller2AnalysisQueue);
-//        IOUtils.closeQuietly(analysisQueue);
+        IOUtils.closeQuietly(analysisQueue);
         IOUtils.closeQuietly(storage);
         super.close();
     }
```

**Comment by MichaelRoeder** [comment]
The bug is not bound to the `feature/leaderboards` branch but comes from a migration to a newer hobbit core library version. Adapted the title accordingly.
