### ISSUE TITLE
Support project sharing and user groups

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#132]
### Description
In Gitlab, the users can be invited into projects. Additionally, they can organize themselfs using groups which also can have there own projects. It would be good if the platform could support this strategy by allowing a user to benchmark systems which are defined in (private) projects to which he has been added or that is owned by a project group that he is a member of.

### Discussion
The main problem is the gathering of this additional information from the Gitlab API. There are two solutions to do that.

#### 1. Sudo method
Gitlab offers a [`sudo` attribute](https://docs.gitlab.com/ce/api/README.html#sudo) that can be used by administrators. Using this attribute together with the method to [list all projects](https://docs.gitlab.com/ce/api/projects.html#list-all-projects) the platform would receive the list of all projects from the point of view of a given user.

**Drawback:** The `sudo` method does not only rely on the authentication as an administrator but also on the presentation of the [`private-token`](https://docs.gitlab.com/ce/api/README.html#private-tokens) of the admin account. Note that this token is more powerful than the [personal access tokens](https://docs.gitlab.com/ce/api/README.html#personal-access-tokens) we are using at the moment.
Although the description of these access tokens state, that they can be used instead of the private token when using the API, it is not working for the `sudo` methods:
```java
    protected List<GitlabProject> getProjectsVisibleForUser(GitlabUser user) throws IOException {
        StringBuilder builder = new StringBuilder();
        builder.append(GitlabUser.URL);
        builder.append('/');
        builder.append(user.getId());
        builder.append("/projects");
        builder.append(new Pagination().withPerPage(Pagination.MAX_ITEMS_PER_PAGE).toString());
        builder.append("&simple=true&sudo=");
        builder.append(user.getId());
        builder.append("&private-token=");
        builder.append(GITLAB_TOKEN);
        System.out.println(builder.toString());
        return api.retrieve().getAll(builder.toString(), GitlabProject[].class);
    }
```
leads to the error
```
Exception in thread "main" java.lang.Error: org.gitlab.api.GitlabAPIException: {"message":"403 Forbidden  - Private token must be specified in order to use sudo"}
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:263)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:217)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:185)
	at org.hobbit.controller.gitlab.GitlabControllerImpl.getProjectsVisibleForUser(GitlabControllerImpl.java:370)
	at org.hobbit.controller.gitlab.GitlabControllerImpl.getProjectsOfUser(GitlabControllerImpl.java:304)
	at org.hobbit.controller.gitlab.GitlabControllerImpl.main(GitlabControllerImpl.java:252)
```

The problem is not bound to the version of the API that we are using (we are using v3 but it behaves the same in v4). We might want to create an issue in Gitlab itself to figure out whether this is a bug or a feature :wink: 

#### 2. Crawl users

It would be possible to request the members of a project (and the members of groups) while crawling the projects. 

**Drawback:** this would cause an additional request per project and an additional data structure to store the mapping between users and projects.

**Comment by MichaelRoeder** [comment]
I created an issue for the drawback of solution 1 at https://forum.gitlab.com/t/api-enforces-usage-of-private-token/11584

**Comment by MichaelRoeder** [comment]
For the drawback of solution 1, there is already an issue that describes it https://gitlab.com/gitlab-org/gitlab-ce/issues/38447. It seems like they are working on a solution, so we might be able to implement solution 1 without any drawbacks.

**Comment by MichaelRoeder** [comment]
The issue in Gitlab has been solved (https://gitlab.com/gitlab-org/gitlab-ce/issues/38447) and the solution has been merged into Gitlab CE master (https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/14838). With the next Gitlab CE release (> v10.1.1), the fix should be available for our Gitlab and we can use solution 1.
