### ISSUE TITLE
Logs about errors about GerbilBenchmarkOKE2015T2 in other benchmark runs

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#160]
Logs about errors in GerbilBenchmarkOKE2015T2 looks strange in the output of non-Gerbil benchmarks: 
```
platform-controller_1  | 2017-11-16 09:56:55,896 INFO [org.hobbit.controller.ExperimentManager] - <Creating next experiment 1510826208706 with benchmark http://project-hobbit.eu/resources/debs2017/debsbenchmark and system http://project-hobbit.eu/resources/debs2017/smirnp-debs17 to the queue.>
platform-controller_1  | 2017-11-16 09:56:55,951 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't find a benchmark resource in the given benchmark meta data model. Returning null.>
platform-controller_1  | 2017-11-16 09:56:55,951 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't get benchmark meta data from "GerbilBenchmarkOKE2015T2".>
platform-controller_1  | 2017-11-16 09:56:56,027 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't find a benchmark resource in the given benchmark meta data model. Returning null.>
platform-controller_1  | 2017-11-16 09:56:56,027 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't get benchmark meta data from "GerbilBenchmarkOKE2015T2".>
platform-controller_1  | 2017-11-16 09:56:56,455 INFO [org.hobbit.controller.docker.LoggingPullHandler] - <Image git.project-hobbit.eu:4567/rkaterinenko/debsbenchmark is up to date und does not have to be pulled.>
platform-controller_1  | 2017-11-16 09:56:56,836 INFO [org.hobbit.controller.docker.LoggingPullHandler] - <Image git.project-hobbit.eu:4567/smirnp/smirnp-debs17 is up to date und does not have to be pulled.>
platform-controller_1  | 2017-11-16 09:56:56,837 ERROR [org.hobbit.controller.ExperimentManager] - <Could not load timeouts config, using default value 1200000ms.>
platform-controller_1  | java.io.FileNotFoundException: config/config.yaml (No such file or directory)
platform-controller_1  |        at java.io.FileInputStream.open0(Native Method)
platform-controller_1  |        at java.io.FileInputStream.open(FileInputStream.java:195)
platform-controller_1  |        at java.io.FileInputStream.<init>(FileInputStream.java:138)
platform-controller_1  |        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:307)
platform-controller_1  |        at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14)
platform-controller_1  |        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2608)
platform-controller_1  |        at org.hobbit.controller.config.HobbitConfig.loadConfig(HobbitConfig.java:35)
platform-controller_1  |        at org.hobbit.controller.config.HobbitConfig.loadConfig(HobbitConfig.java:30)
platform-controller_1  |        at org.hobbit.controller.ExperimentManager.createNextExperiment(ExperimentManager.java:170)
platform-controller_1  |        at org.hobbit.controller.ExperimentManager$1.run(ExperimentManager.java:110)
platform-controller_1  |        at java.util.TimerThread.mainLoop(Timer.java:555)
platform-controller_1  |        at java.util.TimerThread.run(Timer.java:505)
platform-controller_1  | 2017-11-16 09:56:56,838 INFO [org.hobbit.controller.data.ExperimentStatus] - <Creating abort timer for http://w3id.org/hobbit/experiments#1510826208706 with 1200000ms.>
platform-controller_1  | 2017-11-16 09:56:56,848 INFO [org.hobbit.controller.ExperimentManager] - <Creating benchmark controller git.project-hobbit.eu:4567/rkaterinenko/debsbenchmark>
platform-controller_1  | 2017-11-16 09:56:57,257 INFO [org.hobbit.controller.docker.LoggingPullHandler] - <Image git.project-hobbit.eu:4567/rkaterinenko/debsbenchmark is up to date und does not have to be pulled.>
platform-controller_1  | 2017-11-16 09:56:57,258 INFO [com.spotify.docker.client.DefaultDockerClient] - <Creating container with ContainerConfig: ContainerConfig{hostname=debsbenchmark-ad89e4c223154755ae3274ce4e225af9, domainname=null, username=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=null, tty=null, openStdin=null, stdinOnce=null, env=[HOBBIT_CONTAINER_NAME=debsbenchmark-ad89e4c223154755ae3274ce4e225af9, constraint:org.hobbit.workergroup==benchmark, HOBBIT_RABBIT_HOST=rabbit, HOBBIT_SESSION_ID=1510826208706, HOBBIT_EXPERIMENT_URI=http://w3id.org/hobbit/experiments#1510826208706, BENCHMARK_PARAMETERS_MODEL={
....
"involvesBenchmark" : "http://project-hobbit.eu/resources/debs2017/debsbenchmark",
"involvesSystemInstance" : "http://project-hobbit.eu/resources/debs2017/smirnp-debs17",
...

platform-controller_1  | 2017-11-16 09:03:40,304 INFO [com.spotify.docker.client.DefaultDockerClient] - <Starting container with Id: 3fbf7944f998228ff03b84ba02e81727b2cef0f9cec073e7eacde26685e8deaa>
platform-controller_1  | 2017-11-16 09:03:42,447 INFO [org.hobbit.controller.PlatformController] - <Container d01303845a2cd600c7f6ad0a7c3f397699ecbfed2aff3a2ac2f021f81d8744f3 stopped with exitCode=1>
platform-controller_1  | 2017-11-16 09:03:43,121 WARN [org.hobbit.controller.ExperimentManager] - <The benchmark container d01303845a2cd600c7f6ad0a7c3f397699ecbfed2aff3a2ac2f021f81d8744f3 terminated with an exit code != 0.>
platform-controller_1  | 2017-11-16 09:03:43,139 INFO [org.hobbit.controller.ExperimentManager] - <Benchmark terminated. Experiment 1510823012746 has been finished. Removing it from the queue and setting the config to null.>
platform-controller_1  | 2017-11-16 09:03:43,279 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't find a benchmark resource in the given benchmark meta data model. Returning null.>
platform-controller_1  | 2017-11-16 09:03:43,279 ERROR [org.hobbit.controller.docker.ImageManagerImpl] - <Couldn't get benchmark meta data from "conrads / GerbilBenchmarkOKE2015T2".>
platform-controller_1  | stmts to remove: [[http://project-hobbit.eu/resources/debs2017/smirnp-debs17, http://w3id.org/hobbit/vocab#imageName, "git.project-hobbit.eu:4567/smirnp/smirnp-debs17"], [http://project-hobbit.eu/resources/debs2017/debsbenchmark, http://w3id.org/hobbit/vocab#imageName, "git.project-hobbit.eu:4567/rkaterinenko/debsbenchmark"]]
platform-controller_1  | 2017-11-16 09:03:46,347 ERROR [org.hobbit.controller.ExperimentManager] - <Error while storing the result model of the experiment. Logging it: >
platform-controller_1  | 2017-11-16 09:03:46,418 INFO [org.hobbit.controller.PlatformController] - <Container 3fbf7944f998228ff03b84ba02e81727b2cef0f9cec073e7eacde26685e8deaa stopped with exitCode=143>
platform-controller_1  | 2017-11-16 09:03:46,418 INFO [org.hobbit.controller.ExperimentManager] - <Sending broadcast message...>
platform-controller_1  | 2017-11-16 09:03:46,436 INFO [org.hobbit.controller.PlatformController] - <received command: session=BROADCAST, command=DOCKER_CONTAINER_TERMINATED>
```

**Comment by MichaelRoeder** [comment]
The platform goes through all benchmarks because it is searching for a certain information. During this search, it has to parse the benchmark models. However, the GERBIL OKE T2 benchmark can not be parsed as expected (because it does not contain an information that was expected there) and causes the printing of this log message.

An easy solution is to remove this log message. However, we could also think about an optimization of this step so that the access to the information the image manager is searching for is eased (i.e., the manager won't have to look into all benchmarks when it searches a specific one).
