### ISSUE TITLE
Gitlab gateway timeout error

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#222]
The online instance of GitLab does not respond any requests:
```
2018-02-27 10:00:40,279 ERROR [org.hobbit.controller.gitlab.GitlabControllerImpl] - <Couldn't get all gitlab projects.>
platform-controller_1  | org.gitlab.api.GitlabAPIException: <html>
platform-controller_1  | <head><title>504 Gateway Time-out</title></head>
platform-controller_1  | <body bgcolor="white">
platform-controller_1  | <center><h1>504 Gateway Time-out</h1></center>
platform-controller_1  | <hr><center>nginx/1.11.13</center>
platform-controller_1  | </body>
platform-controller_1  | </html>
platform-controller_1  |
platform-controller_1  |        at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:436)
platform-controller_1  |        at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:170)
platform-controller_1  |        at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:139)
platform-controller_1  |        at org.gitlab.api.GitlabAPI.getUser(GitlabAPI.java:147)
platform-controller_1  |        at org.hobbit.controller.gitlab.GitlabControllerImpl$2.run(GitlabControllerImpl.java:130)
platform-controller_1  |        at java.util.TimerThread.mainLoop(Timer.java:555)
platform-controller_1  |        at java.util.TimerThread.run(Timer.java:505)
platform-controller_1  | Caused by: java.io.IOException: Server returned HTTP response code: 504 for URL: https://git.project-hobbit.eu/api/v3/user
platform-controller_1  |        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
platform-controller_1  |        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
platform-controller_1  |        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
platform-controller_1  |        at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:394)
platform-controller_1  |        at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:168)
platform-controller_1  |        ... 5 more
```

**Comment by MichaelRoeder** [comment]
Please try again.

**Comment by smirnp** [comment]
Now it works. Thank you!

**Comment by smirnp** [comment]
It looks like online gitlab is down again. The http://master.project-hobbit.eu/ is also gives empty output.

**Comment by MichaelRoeder** [comment]
Yes. This has been announced by e-mail during the last week. We are working on the servers.
