### ISSUE TITLE
Keycloak can't connect to its database when starting up

### ISSUE THREAD

**Issue by mjovanovik** [hobbit-project/platform#26]
When I try to start Keycloak as part of the platform, using `docker-compose up keycloak`, it fails to start. I get several errors which seem to be caused by a warning I get at the beginning, stating that Keycloak cannot create a connection to its database.

The details about the warning and errors are below.

<details>

```
...
keycloak_1             | 08:26:02,798 WARN  [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool] (ServerService Thread Pool -- 48) IJ000604: Throwable while attempting to get a new connection: null: javax.resource.ResourceException: IJ031084: Unable to create connection
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:343)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:350)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:285)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1319)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:496)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:626)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:598)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:590)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:429)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:747)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
keycloak_1             |        at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:66)
keycloak_1             |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
keycloak_1             |        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:632)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
keycloak_1             |        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:137)
keycloak_1             |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak_1             |        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:130)
keycloak_1             |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak_1             |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak_1             |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak_1             |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
keycloak_1             |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
keycloak_1             |        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
keycloak_1             |        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
keycloak_1             |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak_1             |        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
keycloak_1             |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak_1             |        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
keycloak_1             |        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
keycloak_1             |        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
keycloak_1             |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
keycloak_1             |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
keycloak_1             |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
keycloak_1             |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
keycloak_1             |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak_1             |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak_1             |        at java.lang.Thread.run(Thread.java:745)
keycloak_1             |        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
keycloak_1             | Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || inMemory)" [50100-173]
keycloak_1             |        at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
keycloak_1             |        at org.h2.message.DbException.get(DbException.java:171)
keycloak_1             |        at org.h2.message.DbException.get(DbException.java:148)
keycloak_1             |        at org.h2.message.DbException.getUnsupportedException(DbException.java:206)
keycloak_1             |        at org.h2.engine.Database.open(Database.java:555)
keycloak_1             |        at org.h2.engine.Database.openDatabase(Database.java:226)
keycloak_1             |        at org.h2.engine.Database.<init>(Database.java:221)
keycloak_1             |        at org.h2.engine.Engine.openSession(Engine.java:56)
keycloak_1             |        at org.h2.engine.Engine.openSession(Engine.java:160)
keycloak_1             |        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
keycloak_1             |        at org.h2.engine.Engine.createSession(Engine.java:122)
keycloak_1             |        at org.h2.engine.Engine.createSession(Engine.java:28)
keycloak_1             |        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
keycloak_1             |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
keycloak_1             |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
keycloak_1             |        at org.h2.Driver.connect(Driver.java:73)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
keycloak_1             |        ... 43 more
keycloak_1             |
keycloak_1             | 08:26:02,802 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
keycloak_1             | 08:26:02,808 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 48) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak_1             |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
keycloak_1             |        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
keycloak_1             |        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
keycloak_1             |        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
keycloak_1             |        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
keycloak_1             |        at java.lang.Thread.run(Thread.java:745)
keycloak_1             |        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
keycloak_1             | Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
keycloak_1             |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
keycloak_1             |        at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
keycloak_1             |        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
keycloak_1             |        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
keycloak_1             |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
keycloak_1             |        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
keycloak_1             |        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
keycloak_1             |        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
keycloak_1             |        at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
keycloak_1             |        at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
keycloak_1             |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
keycloak_1             |        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
keycloak_1             |        ... 6 more
keycloak_1             | Caused by: java.lang.RuntimeException: Failed to connect to database
keycloak_1             |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:373)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lazyInit(LiquibaseDBLockProvider.java:65)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.lambda$waitForLock$0(LiquibaseDBLockProvider.java:97)
keycloak_1             |        at org.keycloak.models.utils.KeycloakModelUtils.suspendJtaTransaction(KeycloakModelUtils.java:632)
keycloak_1             |        at org.keycloak.connections.jpa.updater.liquibase.lock.LiquibaseDBLockProvider.waitForLock(LiquibaseDBLockProvider.java:95)
keycloak_1             |        at org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:137)
keycloak_1             |        at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:236)
keycloak_1             |        at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:130)
keycloak_1             |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak_1             |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
keycloak_1             |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak_1             |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
keycloak_1             |        at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
keycloak_1             |        ... 19 more
keycloak_1             | Caused by: java.sql.SQLException: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
keycloak_1             |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:146)
keycloak_1             |        at org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:66)
keycloak_1             |        at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:367)
keycloak_1             |        ... 31 more
keycloak_1             | Caused by: javax.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/KeycloakDS
keycloak_1             |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:656)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:429)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:747)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
keycloak_1             |        ... 33 more
keycloak_1             | Caused by: javax.resource.ResourceException: IJ031084: Unable to create connection
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:343)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:350)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:285)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1319)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:496)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:626)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:598)
keycloak_1             |        at org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:590)
keycloak_1             |        ... 36 more
keycloak_1             | Caused by: org.h2.jdbc.JdbcSQLException: Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == SERIALIZED || inMemory)" [50100-173]
keycloak_1             |        at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
keycloak_1             |        at org.h2.message.DbException.get(DbException.java:171)
keycloak_1             |        at org.h2.message.DbException.get(DbException.java:148)
keycloak_1             |        at org.h2.message.DbException.getUnsupportedException(DbException.java:206)
keycloak_1             |        at org.h2.engine.Database.open(Database.java:555)
keycloak_1             |        at org.h2.engine.Database.openDatabase(Database.java:226)
keycloak_1             |        at org.h2.engine.Database.<init>(Database.java:221)
keycloak_1             |        at org.h2.engine.Engine.openSession(Engine.java:56)
keycloak_1             |        at org.h2.engine.Engine.openSession(Engine.java:160)
keycloak_1             |        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139)
keycloak_1             |        at org.h2.engine.Engine.createSession(Engine.java:122)
keycloak_1             |        at org.h2.engine.Engine.createSession(Engine.java:28)
keycloak_1             |        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:313)
keycloak_1             |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105)
keycloak_1             |        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90)
keycloak_1             |        at org.h2.Driver.connect(Driver.java:73)
keycloak_1             |        at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:319)
keycloak_1             |        ... 43 more
keycloak_1             |
keycloak_1             | 08:26:02,825 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-2) WFLYJCA0010: Unbound data source [java:jboss/datasources/KeycloakDS]
keycloak_1             | 08:26:02,826 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0019: Host default-host stopping
keycloak_1             | 08:26:02,829 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-7) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
keycloak_1             | 08:26:02,830 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0019: Stopped Driver service with driver-name = h2
keycloak_1             | 08:26:02,831 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 48) WFLYCLINF0003: Stopped work cache from keycloak container
keycloak_1             | 08:26:02,831 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 55) WFLYCLINF0003: Stopped authorization cache from keycloak container
keycloak_1             | 08:26:02,831 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 52) WFLYCLINF0003: Stopped loginFailures cache from keycloak container
keycloak_1             | 08:26:02,831 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 49) WFLYCLINF0003: Stopped offlineSessions cache from keycloak container
keycloak_1             | 08:26:02,832 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 54) WFLYCLINF0003: Stopped users cache from keycloak container
keycloak_1             | 08:26:02,831 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 53) WFLYCLINF0003: Stopped keys cache from keycloak container
keycloak_1             | 08:26:02,832 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 51) WFLYCLINF0003: Stopped realms cache from keycloak container
keycloak_1             | 08:26:02,833 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 50) WFLYCLINF0003: Stopped sessions cache from keycloak container
keycloak_1             | 08:26:02,834 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0008: Undertow HTTP listener default suspending
keycloak_1             | 08:26:02,835 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 0.0.0.0:8080
keycloak_1             | 08:26:02,839 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0004: Undertow 1.3.15.Final stopping
keycloak_1             | 08:26:02,850 INFO  [org.hibernate.validator.internal.util.Version] (MSC service thread 1-6) HV000001: Hibernate Validator 5.2.3.Final
keycloak_1             | 08:26:02,897 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0028: Stopped deployment keycloak-server.war (runtime-name: keycloak-server.war) in 86ms
keycloak_1             | 08:26:02,901 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: Keycloak 2.4.0.Final (WildFly Core 2.0.10.Final) stopped in 87ms
keycloak_1             | platform_keycloak_1 exited with code 1
```

</details>

**Comment by mjovanovik** [comment]
I managed to solve the issue. Since the Keycloak docker container gets access to `config/keycloak`, the directory and the `config/keycloak/keycloak.h2.db` database file need to have the correct permission.

Just provide r/w permissions, it will solve the database connection issue.
