### ISSUE TITLE
Docker client crashes because of HTTP connection problems

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#27]
## Problem

When the platform is running for a while, the Java Docker client crashes with an exception like in this example:
```
2017-04-06 14:15:38,486 INFO [com.spotify.docker.client.DefaultDockerClient] - <Creating container with ContainerConfig: ContainerConfig{hostname=defaultevaluationstorag-47aba77264c747319deeeea54ede5920, domainname=null, username=null, attachStdin=null, attachStdout=null, attachStderr=null, portSpecs=null, exposedPorts=null, tty=null, openStdin=null, stdinOnce=null, env=[HOBBIT_CONTAINER_NAME=defaultevaluationstorag-47aba77264c747319deeeea54ede5920, constraint:org.hobbit.type==data, HOBBIT_RIAK_NODES=1, HOBBIT_RABBIT_HOST=rabbit, HOBBIT_RABBIT_HOST=rabbit, HOBBIT_SESSION_ID=1491488115941], cmd=null, image=git.project-hobbit.eu:4567/defaulthobbituser/defaultevaluationstorage:1.0.1, volumes=null, workingDir=null, entrypoint=null, networkDisabled=null, onBuild=null, labels={org.hobbit.parent=61c391ff913aa038681b6d0a1da8116e0cdfe3002b2b504ac034475bbf932e11, org.hobbit.type=data}, macAddress=null, hostConfig=HostConfig{binds=null, containerIDFile=null, lxcConf=null, privileged=null, portBindings=null, links=null, publishAllPorts=null, dns=null, dnsSearch=null, extraHosts=null, volumesFrom=null, capAdd=null, capDrop=null, networkMode=null, securityOpt=null, devices=null, memory=null, memorySwap=null, memoryReservation=null, cpuShares=null, cpusetCpus=null, cpuQuota=null, cgroupParent=null, restartPolicy=null, logConfig=LogConfig{Type=gelf, Config={tag={{.ImageName}}/{{.Name}}/{{.ID}}, gelf-address=udp://hobbit-data.aksw.internal:12201}}, ipcMode=null, ulimits=null, pidMode=null, shmSize=null, oomKillDisable=null, oomScoreAdj=null}, stopSignal=null}>
2017-04-06 14:15:43,553 ERROR [org.hobbit.controller.docker.ContainerManagerImpl] - <Couldn't create Docker container. Returning null.>
com.spotify.docker.client.exceptions.DockerTimeoutException: Timeout: POST http://swarm-master:4000/networks/hobbit/connect
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2027)
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2080)
	at com.spotify.docker.client.DefaultDockerClient.manageNetworkConnection(DefaultDockerClient.java:1885)
	at com.spotify.docker.client.DefaultDockerClient.connectToNetwork(DefaultDockerClient.java:1868)
	at org.hobbit.controller.PlatformController.receiveCommand(PlatformController.java:252)
	at org.hobbit.controller.docker.ContainerManagerImpl.createContainer(ContainerManagerImpl.java:341)
	at org.hobbit.controller.PlatformController.createContainer(PlatformController.java:330)
	at org.hobbit.controller.docker.ContainerManagerImpl.startContainer(ContainerManagerImpl.java:372)
	at org.hobbit.core.components.AbstractCommandReceivingComponent$1.handleDelivery(AbstractCommandReceivingComponent.java:95)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at org.hobbit.controller.PlatformController.handleCmd(PlatformController.java:478)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at java.lang.Thread.run(Thread.java:745)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2025)
	... 13 more
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:286)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 more
```

It seems like the used HTTP client can not get an HTTP connection from its connection pool which is a hint that there are open connections that are not freed (see for example http://stackoverflow.com/questions/11875015/httpclient-exception-org-apache-http-conn-connectionpooltimeoutexception-timeo).

## Possible solutions
Increasing the pool could solve the problem if the connections need some more time to get freed. However, a better solution might be to check why connections seem to be left open.

**Comment by MichaelRoeder** [comment]
not valid for the new swarm, anymore.
