### ISSUE TITLE
GUI building problem

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#286]
Hi!

I'm doing `npm run build` and get the following error (below)

```
Hash: ba6e91a12afdd8e912ae
Time: 31834ms
chunk    {0} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 195 kB {5} [initial] [rendered]
chunk    {1} main.bundle.js, main.bundle.js.map (main) 163 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 212 kB {5} [initial] [rendered]
chunk    {3} scripts.bundle.js, scripts.bundle.js.map (scripts) 463 kB {5} [initial] [rendered]
chunk    {4} vendor.bundle.js, vendor.bundle.js.map (vendor) 4.63 MB [initial] [rendered]
chunk    {5} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]
ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/browserslist/index.js:320:18)
    at Function.select (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/browserslist/index.js:438:37)
    at /home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/browserslist/index.js:207:41
    at Array.forEach (native)
    at browserslist (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:228:20)
    at LazyResult.async (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:225:27)
    at LazyResult.then (/home/vagrant/Projects/hobbit-platform-1.0.16/hobbit-gui/gui-client/node_modules/postcss/lib/lazy-result.js:131:21)
 @ ./~/bootstrap/dist/css/bootstrap.min.css 4:14-127
 @ multi ./src/styles.css ./~/bootstrap/dist/css/bootstrap.min.css ./~/font-awesome/css/font-awesome.css ./~/ng2-slim-loading-bar/bundles/style.css ./~/primeng/resources/primeng.min.css ./~/primeng/resources/themes/bootstrap/theme.css
```

**Comment by MichaelRoeder** [comment]
Is there a reason to use version `1.0.16`? Otherwise, I would suggest to use the latest version.

**Comment by smirnp** [comment]
v2.04 is the latest? Is that deployed online?

**Comment by MichaelRoeder** [comment]
yes. The images are available at https://hub.docker.com/u/hobbitproject/

**Comment by smirnp** [comment]
Ok. Thank you!
