### ISSUE TITLE
Default evaluation storage is missing a good strategy for large results

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#33]
## Problem
The default evaluation storage implementation is not applicable for larger responses. The following stacktrace shows an exception that is thrown for a result that has a size > 300MB.

```
April 26th 2017, 14:00:12.937	basho-riak-k	2017-04-26 12:00:12.937 [error] <0.1351.0>@riak_kv_vnode:encode_and_put_no_sib_check:2356 Put failure: object too large to write <<"ACTUAL">>/<<"13">> 307718474 bytes
April 26th 2017, 14:00:12.937	defaultevaluationstorag	java.util.concurrent.ExecutionException: com.basho.riak.client.core.netty.RiakResponseException: {too_large,307718474}
April 26th 2017, 14:00:12.937	defaultevaluationstorag		at com.basho.riak.client.core.FutureOperation.get(FutureOperation.java:260)
April 26th 2017, 14:00:12.938	defaultevaluationstorag		at com.basho.riak.client.api.RiakCommand.execute(RiakCommand.java:89)
April 26th 2017, 14:00:12.938	defaultevaluationstorag		at com.basho.riak.client.api.commands.CoreFutureAdapter.get(CoreFutureAdapter.java:52)
April 26th 2017, 14:00:12.940	defaultevaluationstorag		at org.hobbit.evaluationstorage.resultstore.RiakResultStoreFacade.put(RiakResultStoreFacade.java:168)
April 26th 2017, 14:00:12.940	defaultevaluationstorag		at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
April 26th 2017, 14:00:12.940	defaultevaluationstorag		at com.basho.riak.client.api.RiakClient.execute(RiakClient.java:293)
April 26th 2017, 14:00:12.940	defaultevaluationstorag		at org.hobbit.core.components.AbstractEvaluationStorage$2.handleDelivery(AbstractEvaluationStorage.java:128)
April 26th 2017, 14:00:12.940	defaultevaluationstorag		at org.hobbit.evaluationstorage.EvaluationStorage.receiveResponseData(EvaluationStorage.java:83)
April 26th 2017, 14:00:12.941	defaultevaluationstorag		at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
April 26th 2017, 14:00:12.941	defaultevaluationstorag		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
April 26th 2017, 14:00:12.943	defaultevaluationstorag		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
April 26th 2017, 14:00:12.943	defaultevaluationstorag		at java.lang.Thread.run(Thread.java:745)
April 26th 2017, 14:00:12.943	defaultevaluationstorag	Caused by: com.basho.riak.client.core.netty.RiakResponseException: {too_large,307718474}
April 26th 2017, 14:00:12.944	defaultevaluationstorag		at com.basho.riak.client.core.netty.RiakResponseHandler.channelRead(RiakResponseHandler.java:54)
April 26th 2017, 14:00:12.944	defaultevaluationstorag		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:155)
April 26th 2017, 14:00:12.944	defaultevaluationstorag		at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
April 26th 2017, 14:00:12.944	defaultevaluationstorag		at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
April 26th 2017, 14:00:12.947	defaultevaluationstorag		at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:326)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:340)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:116)
April 26th 2017, 14:00:12.950	defaultevaluationstorag		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
April 26th 2017, 14:00:12.951	defaultevaluationstorag		at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
April 26th 2017, 14:00:12.951	defaultevaluationstorag		... 1 more
```

## Solution
Every storage entry should have a flag that is used as follows
* for small results, the flag is set to `0` and the result is stored directly in the KV store
* for large results, the flag is set to `1`, the result is stored on the disk and the file name is stored in the KV store

**Comment by MichaelRoeder** [comment]
## Reproduction
* Create an instance of a `DefaultEvaluationStorage` (code can be found at https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractBenchmarkController.java#L269 ). Note that it will assume a `Constants.RABBIT_MQ_HOST_NAME_KEY` and a `Constants.HOBBIT_SESSION_ID_KEY`
* Connect to the evaluation store pretending either to be a system or a task generator
    * create a queue
        * https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractSystemAdapter.java#L185-L186 OR
        * https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractTaskGenerator.java#L155-L156
    * send a huge message
        * https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractSystemAdapter.java#L228-L243 OR
        * https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractTaskGenerator.java#L310-L319

The solution can be implemented in the AbstractEvaluationStorage class in the core library (https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/AbstractEvaluationStorage.java). This enables the possibility to have a JUnit test using the in-memory implementation of this abstract class (https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/core/components/test/InMemoryEvaluationStore.java)

**Comment by yamalight** [comment]
@MichaelRoeder create new PR here: https://github.com/hobbit-project/evaluation-storage/pull/1

**Comment by MichaelRoeder** [comment]
Fixed with https://github.com/hobbit-project/evaluation-storage/releases/tag/v1.0.4
