### ISSUE TITLE
Gitlab communication problem

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#352]
## Description

Because of a problem in Docker Swarm, the Gitlab service has been recreated. Following the docker-compose file, Docker has fetched the latest image. However, it looks like the latest version does not support API v3 any more.

Moving back to an older version did not solve the problem.
```
gitlab/gitlab-ce@sha256:35a19926f866a53f7435f31ef8300e71e09a45174ac16804a44bd99a3c771b95
```
Until now, Gitlab can be called by the platform. However, the UI is responding with HTTP 500.

**Comment by smirnp** [comment]
While plafform controller gets all the projects and executes benchmarks it shows the following exceptions:
```
2018-10-17 09:55:30,475 ERROR [org.hobbit.controller.gitlab.GitlabControllerImpl] - <Couldn't get all gitlab projects.>
platform-controller_1 | java.io.FileNotFoundException: https://git.project-hobbit.eu/api/v3/user
platform-controller_1 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
platform-controller_1 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
platform-controller_1 | at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:394)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:168)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:139)
platform-controller_1 | at org.gitlab.api.GitlabAPI.getUser(GitlabAPI.java:147)
platform-controller_1 | at org.hobbit.controller.gitlab.GitlabControllerImpl$2.run(GitlabControllerImpl.java:148)
platform-controller_1 | at java.util.TimerThread.mainLoop(Timer.java:555)
platform-controller_1 | at java.util.TimerThread.run(Timer.java:505)
platform-controller_1 | 2018-10-17 09:56:30,484 ERROR [org.hobbit.controller.gitlab.GitlabControllerImpl] - <Couldn't get all gitlab projects.>
platform-controller_1 | java.io.FileNotFoundException: https://git.project-hobbit.eu/api/v3/user
platform-controller_1 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
platform-controller_1 | at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
platform-controller_1 | at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:394)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:168)
platform-controller_1 | at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:139)
platform-controller_1 | at org.gitlab.api.GitlabAPI.getUser(GitlabAPI.java:147)
platform-controller_1 | at org.hobbit.controller.gitlab.GitlabControllerImpl$2.run(GitlabControllerImpl.java:148)
platform-controller_1 | at java.util.TimerThread.mainLoop(Timer.java:555)
platform-controller_1 | at java.util.TimerThread.run(Timer.java:505)
```

**Comment by MichaelRoeder** [comment]
We updated the Gitlab version and the gitlab client we are using.
