### ISSUE TITLE
Storage service errors

### ISSUE THREAD

**Issue by smirnp** [hobbit-project/platform#357]
Hi, 

The storage service (latest) gives the following errors when resultModel should be saved:

```
2018-10-24 11:26:10,400 ERROR [org.hobbit.storage.service.DeliveryProcessing] - <Exception while calling SPARQL endpoint.>
org.apache.jena.query.QueryParseException: Could not initialize class org.apache.jena.query.ARQ
	at org.apache.jena.sparql.lang.ParserSPARQL11Update._parse(ParserSPARQL11Update.java:79)
	at org.apache.jena.sparql.lang.ParserSPARQL11Update.parse$(ParserSPARQL11Update.java:40)
	at org.apache.jena.sparql.lang.UpdateParser.parse(UpdateParser.java:39)
	at org.apache.jena.update.UpdateFactory.make(UpdateFactory.java:87)
	at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:78)
	at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:56)
	at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:46)
	at org.hobbit.storage.service.StorageService.callSparqlEndpoint(StorageService.java:151)
	at org.hobbit.storage.service.DeliveryProcessing.run(DeliveryProcessing.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.jena.query.ARQ
	at org.apache.jena.sparql.lang.ParserBase.<init>(ParserBase.java:291)
	at org.apache.jena.sparql.lang.SPARQLParserBase.<init>(SPARQLParserBase.java:43)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11Base.<init>(SPARQLParser11Base.java:22)
	at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.<init>(SPARQLParser11.java:4974)
	at org.apache.jena.sparql.lang.ParserSPARQL11Update._parse(ParserSPARQL11Update.java:57)
	... 11 more

```

**Comment by denkv** [comment]
Could you give more details the way you run the platform?

It works for me after building local images (with `make build`) and using `docker-compose-dev.yml`.

**Comment by smirnp** [comment]
I'm not building it, but using the default from the docker-compose file: hobbitproject/hobbit-storage-service:latest

**Comment by smirnp** [comment]
```
docker-compose -f docker-compose-dev.yml build
```
Gives the following:
```
platform-controller uses an image, skipping
gui uses an image, skipping
keycloak uses an image, skipping
analysis uses an image, skipping
rabbit uses an image, skipping
redis uses an image, skipping
vos uses an image, skipping
storage-service uses an image, skipping

```

**Comment by denkv** [comment]
I've updated `:latest` images on docker hub now.

**Comment by smirnp** [comment]
Now it works. Thanks!
