### ISSUE TITLE
Can not start benchmark successfully

### ISSUE THREAD

**Issue by xhulja07** [hobbit-project/platform#439]
Hello, can anyone help me with this error I get when I start the experiment?
From the console I get this log:
```
2019-07-08 18:05:13,574 INFO [org.hobbit.controller.docker.ContainerManagerImpl] - <Container z44413zrn6dyrxtcue783mysg created>
platform-controller_1  | 2019-07-08 18:05:13,575 INFO [org.hobbit.controller.ExperimentManager] - <Creating system git.project-hobbit.eu:4567/xhulja_shahini/juliabenchmark/system-adapter>
platform-controller_1  | 2019-07-08 18:05:13,577 INFO [org.hobbit.controller.docker.ContainerManagerImpl] - <Pulling the image "git.project-hobbit.eu:4567/xhulja_shahini/juliabenchmark/system-adapter">
platform-controller_1  | 2019-07-08 18:05:13,600 INFO [org.hobbit.controller.docker.ContainerManagerImpl] - <Pulling service id: vm2ufirbni4uio3d0w6cz44ch>
platform-controller_1  | 2019-07-08 18:05:15,421 INFO [org.hobbit.controller.docker.ContainerManagerImpl] - <Swarm pulled the image "git.project-hobbit.eu:4567/xhulja_shahini/juliabenchmark/system-adapter" (complete)>
platform-controller_1  | 2019-07-08 18:05:15,506 WARN [org.hobbit.controller.docker.ContainerManagerImpl] - <The swarm cluster got only 1 node, I will not use placement constraints.>
platform-controller_1  | 2019-07-08 18:05:16,344 INFO [org.hobbit.controller.PlatformController] - <Container z44413zrn6dyrxtcue783mysg stopped with exitCode=255>
platform-controller_1  | 2019-07-08 18:05:17,586 INFO [org.hobbit.controller.docker.ContainerManagerImpl] - <Container oocqm50vpmslvkyus4jlo0y29 created>
platform-controller_1  | 2019-07-08 18:05:17,586 WARN [org.hobbit.controller.ExperimentManager] - <The benchmark container z44413zrn6dyrxtcue783mysg terminated with an exit code != 0.>
platform-controller_1  | 2019-07-08 18:05:17,599 INFO [org.hobbit.controller.ExperimentManager] - <Benchmark terminated. Experiment 1562609094612 has been finished. Removing it from the queue and setting the config to null.>
platform-controller_1  | 2019-07-08 18:05:17,694 ERROR [org.hobbit.controller.docker.ResourceInformationCollectorImpl] - <Error while requesting Prometheus>
platform-controller_1  | java.net.ConnectException: Connection refused (Connection refused)
```

The error I get from the logs:
[1562607070640 benchmark log.txt](https://github.com/hobbit-project/platform/files/3369767/1562607070640.benchmark.log.txt)

**Comment by xhulja07** [comment]
the problem was in the benchmark.ttl file

**Comment by xhulja07** [comment]
Look like the platform is trying to get some model value from rabbitmq and fails 
![image](https://user-images.githubusercontent.com/11543623/60884454-33fe5c00-a24d-11e9-832e-c34a9ddd7050.png)

**Comment by MichaelRoeder** [comment]
1. you can ignore the message regarding Prometheus as long as the benchmark is not relying on the measurement of resources used by the benchmarked system (e.g., CPU time or RAM).

2. The error in your benchmark controller is caused by the jena library which tries to read some meta values during its initialization phase.
```
@timestamp image_name container_name message
2019-07-08T17:31:28.032Z benchmark-controller:latest  Caused by: java.lang.NullPointerException
2019-07-08T17:31:28.032Z benchmark-controller:latest  	at org.apache.jena.riot.system.RiotLib.<clinit>(RiotLib.java:60)
2019-07-08T17:31:28.032Z benchmark-controller:latest  	... 13 more
2019-07-08T17:31:28.032Z benchmark-controller:latest  2019-07-08 17:31:28,003 DEBUG [org.hobbit.sdk.examples.juliabenchmark.benchmark.BenchmarkController] - <close()>
2019-07-08T17:31:28.032Z benchmark-controller:latest  	at org.apache.jena.query.ARQ.isTrue(ARQ.java:640)
2019-07-08T17:31:28.030Z benchmark-controller:latest  	... 6 more
2019-07-08T17:31:28.030Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getVariableValue(EnvVariables.java:60)
2019-07-08T17:31:28.030Z benchmark-controller:latest  	at org.hobbit.core.rabbit.RabbitMQUtils.readModel(RabbitMQUtils.java:103)
2019-07-08T17:31:28.030Z benchmark-controller:latest  	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:310)
2019-07-08T17:31:28.029Z benchmark-controller:latest  	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:880)
2019-07-08T17:31:28.029Z benchmark-controller:latest  Caused by: java.lang.ExceptionInInitializerError
2019-07-08T17:31:28.029Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.buildFactoryRDF(RDFParserBuilder.java:572)
2019-07-08T17:31:28.029Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.build(RDFParserBuilder.java:544)
2019-07-08T17:31:28.029Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
2019-07-08T17:31:28.028Z benchmark-controller:latest  	at org.hobbit.core.components.AbstractBenchmarkController.init(AbstractBenchmarkController.java:149)
2019-07-08T17:31:28.028Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModel(EnvVariables.java:321)
2019-07-08T17:31:28.028Z benchmark-controller:latest  	at org.hobbit.sdk.examples.juliabenchmark.benchmark.BenchmarkController.init(BenchmarkController.java:21)
2019-07-08T17:31:28.028Z benchmark-controller:latest  	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:61)
2019-07-08T17:31:28.026Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModelValue(EnvVariables.java:392)
2019-07-08T17:31:28.026Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModelValue(EnvVariables.java:423)
2019-07-08T17:31:28.010Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getVariableValue(EnvVariables.java:77)
2019-07-08T17:31:28.009Z benchmark-controller:latest  	at org.apache.jena.riot.system.RiotLib.<clinit>(RiotLib.java:60)
2019-07-08T17:31:28.009Z benchmark-controller:latest  	... 13 more
2019-07-08T17:31:28.009Z benchmark-controller:latest  java.lang.IllegalStateException: Error while reading the value of the variable BENCHMARK_PARAMETERS_MODEL. Aborting.
2019-07-08T17:31:28.009Z benchmark-controller:latest  	at org.apache.jena.query.ARQ.isTrue(ARQ.java:640)
2019-07-08T17:31:28.009Z benchmark-controller:latest  Caused by: java.lang.NullPointerException
2019-07-08T17:31:28.009Z benchmark-controller:latest  2019-07-08 17:31:27,999 ERROR [org.hobbit.core.run.ComponentStarter] - <Exception while executing component. Exiting with error code.>
2019-07-08T17:31:28.007Z benchmark-controller:latest  	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:61)
2019-07-08T17:31:28.007Z benchmark-controller:latest  	at org.hobbit.core.components.AbstractBenchmarkController.init(AbstractBenchmarkController.java:149)
2019-07-08T17:31:28.007Z benchmark-controller:latest  	at org.hobbit.sdk.examples.juliabenchmark.benchmark.BenchmarkController.init(BenchmarkController.java:21)
2019-07-08T17:31:28.006Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModelValue(EnvVariables.java:423)
2019-07-08T17:31:28.006Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModelValue(EnvVariables.java:392)
2019-07-08T17:31:28.006Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getModel(EnvVariables.java:321)
2019-07-08T17:31:28.006Z benchmark-controller:latest  	at org.hobbit.utils.EnvVariables.getVariableValue(EnvVariables.java:60)
2019-07-08T17:31:28.002Z benchmark-controller:latest  	at org.hobbit.core.rabbit.RabbitMQUtils.readModel(RabbitMQUtils.java:103)
2019-07-08T17:31:28.000Z benchmark-controller:latest  java.lang.ExceptionInInitializerError
2019-07-08T17:31:28.000Z benchmark-controller:latest  	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:310)
2019-07-08T17:31:28.000Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.build(RDFParserBuilder.java:544)
2019-07-08T17:31:28.000Z benchmark-controller:latest  	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:880)
2019-07-08T17:31:28.000Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.buildFactoryRDF(RDFParserBuilder.java:572)
2019-07-08T17:31:28.000Z benchmark-controller:latest  	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
2019-07-08T17:31:27.999Z benchmark-controller:latest  2019-07-08 17:31:27,997 ERROR [org.hobbit.core.components.AbstractBenchmarkController] - <Error while reading the value of the variable BENCHMARK_PARAMETERS_MODEL. Aborting.>
2019-07-08T17:31:27.714Z benchmark-controller:latest  2019-07-08 17:31:27,715 DEBUG [Jena] - <Jena initialization>
```
Based on similar issues that I saw before, I would suggest that you double check the build process of your jar library. To me, it seems like it is not copying all the data form the META directory of the single libraries which leads to the situation that one of the jena libraries would like to load a parameter that is not available.

If you take a look at the `pom.xml` we propose, you can see that the shade plugin configured to use two "transformers" which should take care of copying this information into your META directory (https://hobbit-project.github.io/java_components.html#project-creation).

**Comment by xhulja07** [comment]
thank you. rebuilding solved the issue
