### ISSUE TITLE
Evaluation Storage crashes

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#58]
## Problem

The evaluation storage crashes when it has not received expected responses. When the evaluation starts, it tries to iterate over files of the directory containing the expected reponeses. However, the directory might not have been created and the iteration fails with a `NullPointerException`.

```
...
 INFO [main] (RiakResultStoreFacade.java:128) - Got "OK" from "http://basho-riak-k-fbca27213a984800899b382c02d803e5:8098/ping"
 INFO [main] (RiakResultStoreFacade.java:121) - Finished setting up a Riak cluster with 1 nodes.
 INFO [main] (RiakNode.java:288) - RiakNode started; basho-riak-k-fbca27213a984800899b382c02d803e5:8087
 INFO [main] (RiakCluster.java:180) - RiakCluster is starting.
 INFO [main] (RiakResultStoreFacade.java:207) - Waiting for cluster stabilitation...
 INFO [main] (FileResultStoreFacade.java:25) - Setting up file facade...
 INFO [pool-1-thread-5] (AbstractEvaluationStorage.java:159) - Creating new iterator #0
com.rabbitmq.client.impl.DefaultExceptionHandler: Consumer org.hobbit.core.components.AbstractEvaluationStorage$3@1fe95b0f (amq.ctag-hXDd443OsWwhugEUt9CEAw) method handleDelivery for channel AMQChannel(amqp://guest@172.19.0.3:5672/,4) threw an exception for channel AMQChannel(amqp://guest@172.19.0.3:5672/,4):
java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at org.hobbit.evaluationstorage.resultstore.FileResultStoreFacade.createIterator(FileResultStoreFacade.java:77)
        at org.hobbit.evaluationstorage.EvaluationStorage.createIterator(EvaluationStorage.java:106)
        at org.hobbit.core.components.AbstractEvaluationStorage$3.handleDelivery(AbstractEvaluationStorage.java:160)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by MichaelRoeder** [comment]
It might also be possible, that it fails because it did not receive any __long__ results and stores all results in the RIAK store.

**Comment by MichaelRoeder** [comment]
Should be fixed with https://github.com/hobbit-project/evaluation-storage/commit/ef6aedaae8271fa09f3f150d66d449777eda5e6a

**Comment by MichaelRoeder** [comment]
The call of the `init()` method for the file-based storage has been missing. fixed that in https://github.com/hobbit-project/evaluation-storage/commit/741ce11a0c0748d79fcb1daae5fa070e79c8e31f
