### ISSUE TITLE
GUI always needs Internet access

### ISSUE THREAD

**Issue by MichaelRoeder** [hobbit-project/platform#8]
It is not possible to start the plattform in a local network that has no internet connection because the GUI crashes.

```
gui_1                  | 2016-12-07 08:27:02.437:WARN:oejs.HttpChannel:qtp1192108080-16: //localhost:8080/rest/internal/keycloak-config
gui_1                  | javax.servlet.ServletException: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: de.usu.research.hobbit.gui.rabbitmq.GUIBackendException: Error on retrieving Keycloak configuration: java.net.UnknownHostException: www.eclipse.org
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:139)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  | 	at org.eclipse.jetty.server.Server.handle(Server.java:523)
gui_1                  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
gui_1                  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
gui_1                  | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  | 	at java.lang.Thread.run(Thread.java:745)
gui_1                  | Caused by: 
gui_1                  | javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: de.usu.research.hobbit.gui.rabbitmq.GUIBackendException: Error on retrieving Keycloak configuration: java.net.UnknownHostException: www.eclipse.org
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
gui_1                  | 	at de.usu.research.hobbit.gui.util.ConnectionShutdownFilter.doFilter(ConnectionShutdownFilter.java:19)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
gui_1                  | 	at de.usu.research.hobbit.gui.util.CorsFilter.doFilter(CorsFilter.java:24)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
gui_1                  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  | 	at org.eclipse.jetty.server.Server.handle(Server.java:523)
gui_1                  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
gui_1                  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
gui_1                  | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  | 	at java.lang.Thread.run(Thread.java:745)
gui_1                  | Caused by: 
gui_1                  | org.glassfish.jersey.server.ContainerException: de.usu.research.hobbit.gui.rabbitmq.GUIBackendException: Error on retrieving Keycloak configuration: java.net.UnknownHostException: www.eclipse.org
gui_1                  | 	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
gui_1                  | 	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
gui_1                  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
gui_1                  | 	at de.usu.research.hobbit.gui.util.ConnectionShutdownFilter.doFilter(ConnectionShutdownFilter.java:19)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
gui_1                  | 	at de.usu.research.hobbit.gui.util.CorsFilter.doFilter(CorsFilter.java:24)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
gui_1                  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  | 	at org.eclipse.jetty.server.Server.handle(Server.java:523)
gui_1                  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
gui_1                  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
gui_1                  | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  | 	at java.lang.Thread.run(Thread.java:745)
gui_1                  | Caused by: 
gui_1                  | de.usu.research.hobbit.gui.rabbitmq.GUIBackendException: Error on retrieving Keycloak configuration: java.net.UnknownHostException: www.eclipse.org
gui_1                  | 	at de.usu.research.hobbit.gui.rest.InternalResources.getKeycloakConfig(InternalResources.java:59)
gui_1                  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gui_1                  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gui_1                  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gui_1                  | 	at java.lang.reflect.Method.invoke(Method.java:498)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
gui_1                  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
gui_1                  | 	at de.usu.research.hobbit.gui.util.ConnectionShutdownFilter.doFilter(ConnectionShutdownFilter.java:19)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
gui_1                  | 	at de.usu.research.hobbit.gui.util.CorsFilter.doFilter(CorsFilter.java:24)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
gui_1                  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  | 	at org.eclipse.jetty.server.Server.handle(Server.java:523)
gui_1                  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
gui_1                  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
gui_1                  | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  | 	at java.lang.Thread.run(Thread.java:745)
gui_1                  | Caused by: 
gui_1                  | java.net.UnknownHostException: www.eclipse.org
gui_1                  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
gui_1                  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
gui_1                  | 	at java.net.Socket.connect(Socket.java:589)
gui_1                  | 	at java.net.Socket.connect(Socket.java:538)
gui_1                  | 	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
gui_1                  | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
gui_1                  | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
gui_1                  | 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
gui_1                  | 	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
gui_1                  | 	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
gui_1                  | 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
gui_1                  | 	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
gui_1                  | 	at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
gui_1                  | 	at org.apache.xerces.impl.XMLEntityManager.startDTDEntity(Unknown Source)
gui_1                  | 	at org.apache.xerces.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
gui_1                  | 	at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
gui_1                  | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
gui_1                  | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
gui_1                  | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
gui_1                  | 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
gui_1                  | 	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
gui_1                  | 	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
gui_1                  | 	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
gui_1                  | 	at de.usu.research.hobbit.gui.rest.InternalResources.findKeycloakConfig(InternalResources.java:124)
gui_1                  | 	at de.usu.research.hobbit.gui.rest.InternalResources.getKeycloakConfig(InternalResources.java:50)
gui_1                  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gui_1                  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gui_1                  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gui_1                  | 	at java.lang.reflect.Method.invoke(Method.java:498)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
gui_1                  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
gui_1                  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
gui_1                  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
gui_1                  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
gui_1                  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
gui_1                  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
gui_1                  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
gui_1                  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
gui_1                  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
gui_1                  | 	at de.usu.research.hobbit.gui.util.ConnectionShutdownFilter.doFilter(ConnectionShutdownFilter.java:19)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
gui_1                  | 	at de.usu.research.hobbit.gui.util.CorsFilter.doFilter(CorsFilter.java:24)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
gui_1                  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
gui_1                  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
gui_1                  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
gui_1                  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
gui_1                  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
gui_1                  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
gui_1                  | 	at org.eclipse.jetty.server.Server.handle(Server.java:523)
gui_1                  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
gui_1                  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
gui_1                  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
gui_1                  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
gui_1                  | 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
gui_1                  | 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
gui_1                  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
gui_1                  | 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by PyroIgnus** [comment]
Has this issue been resolved yet or is there a workaround for it?  My team has encountered this issue while trying to start the HOBBIT GUI.

**Comment by MichaelRoeder** [comment]
The only solution is to grant internet access to the platform. Please note that this is required because of #9 anyway. 

As long as the platform controller requires internet access, the issue regarding the gui has a low priority.

**Comment by Ennosigaeon** [comment]
This issue is caused by the jetty configuration files. These xml files include `<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_3.dtd">` as a schema. A possible solution would be downloading the dtd file, adding it to the jar file and referencing it in the jetty configurations.  However, i am not sure whether this is still relevant.

**Comment by Ennosigaeon** [comment]
@MichaelRoeder Can this issue be closed? The platform is not really useful without internet access.

**Comment by MichaelRoeder** [comment]
No, please leave it as it is. In the future, we would like to offer the platform without using our gitlab (#9).

**Comment by joakime** [comment]
It seems that your project cannot find the XML entities for System ID and Public ID that ship with the Jetty Jars.
Are you mangling the Jetty jars in any way? (assembly plugin? shade plugin? uber jar? etc)

**Comment by joakime** [comment]
Jetty version 9.3.13.v20161014 was declared End of Life back back in mid 2020.
Jetty 9.3.13.v20161014 is also subject to a few vulnerabilities  
See: https://www.eclipse.org/jetty/security_reports.php

https://github.com/hobbit-project/platform/blob/master/hobbit-gui/gui-serverbackend/pom.xml#L37

https://github.com/hobbit-project/platform/blob/7b6e394ca32ee7a126644956c09350853e79e4bc/hobbit-gui/gui-serverbackend/pom.xml#L37

Jetty versions 9.4.x are now at End of Community Support.
See: https://github.com/eclipse/jetty.project/issues/7958

You should be using Jetty 10.x, or Jetty 11.x
